# Generated by Django 3.2.12 on 2022-03-01 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followrequest',
            name='summmary',
        ),
        migrations.AddField(
            model_name='followrequest',
            name='summary',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.UUIDField(default='7e62dc38ba8c459a9e288370e5a074a4', editable=False, primary_key=True, serialize=False),
        ),
    ]
