# Generated by Django 3.2.12 on 2022-03-24 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author_url',
            field=models.URLField(default=3, editable=False, max_length=1000),
            preserve_default=False,
        ),
    ]
