# Generated by Django 3.2.12 on 2022-03-01 20:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followrequest',
            old_name='summmary',
            new_name='summary',
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
