# Generated by Django 3.2.12 on 2022-03-03 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.UUIDField(default='549ec232527b4ea686e27ab92273969c', editable=False, primary_key=True, serialize=False),
        ),
    ]
