# Generated by Django 3.2.12 on 2022-03-07 23:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='object_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='like',
            name='object_type',
            field=models.CharField(choices=[('POST', 'Post'), ('COMMENT', 'Comment'), ('AUTHOR', 'Author')], default='POST', max_length=7),
        ),
    ]
