# Generated by Django 3.2.12 on 2022-02-22 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='user_id',
            field=models.CharField(default='', editable=False, max_length=64, primary_key=True, serialize=False, unique=True),
        ),
    ]
