# Generated by Django 3.1.6 on 2022-03-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.UUIDField(default='ec61a33091b94bfab4de6fd0564f4018', editable=False, primary_key=True, serialize=False),
        ),
    ]
