# Generated by Django 3.1.6 on 2022-03-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0002_auto_20220303_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(default='', max_length=1100),
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.UUIDField(default='0644ca7a66b24c9d83b9c4543dd13cd6', editable=False, primary_key=True, serialize=False),
        ),
    ]
