# Generated by Django 3.2.12 on 2022-03-07 23:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0002_auto_20220307_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='object_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
