# Generated by Django 3.2.12 on 2022-03-23 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0002_remove_post_recepient'),
    ]

    operations = [
        migrations.AddField(
            model_name='followrequest',
            name='from_author_url',
            field=models.URLField(default=1, editable=False, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='followrequest',
            name='to_author_url',
            field=models.URLField(default=1, editable=False, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='followrequest',
            name='from_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_request_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='followrequest',
            name='to_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_request_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
