# Generated by Django 3.2.12 on 2022-03-25 09:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0003_alter_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboxitem',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
