# Generated by Django 3.2.12 on 2022-03-08 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0003_alter_like_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
        migrations.RemoveField(
            model_name='like',
            name='summary',
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='like',
            name='object_type',
            field=models.CharField(choices=[('POST', 'Post'), ('COMMENT', 'Comment')], default='POST', max_length=7),
        ),
    ]
