# Generated by Django 3.2.12 on 2022-03-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0003_auto_20220323_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboxitem',
            name='object_url',
            field=models.URLField(default=None, editable=False, max_length=1000, null=True),
        ),
    ]
