# Generated by Django 3.2.12 on 2022-02-22 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0003_auto_20220222_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='followers',
            field=models.ManyToManyField(related_name='_social_distribution_author_followers_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='author',
            name='following',
            field=models.ManyToManyField(related_name='_social_distribution_author_following_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FollowRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summmary', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('from_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_request_from', to=settings.AUTH_USER_MODEL)),
                ('to_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_request_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
