# Generated by Django 3.2.12 on 2022-04-03 08:23

from django.db import migrations, models
import social_distribution.models


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0004_inboxitem_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='recipient',
            field=models.UUIDField(default=None, null=True, verbose_name=social_distribution.models.Author),
        ),
    ]
