# Generated by Django 3.2.12 on 2022-03-09 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0005_auto_20220309_0216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followrequest',
            name='summary',
        ),
    ]
