# Generated by Django 3.1.6 on 2022-02-23 06:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0005_auto_20220223_0610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date',
        ),
        migrations.AddField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
