# Generated by Django 3.2.12 on 2022-04-04 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0005_follower'),
        ('social_distribution', '0005_post_recipient'),
    ]

    operations = [
    ]
