# Generated by Django 3.2.12 on 2022-04-04 08:10

from django.db import migrations, models
import social_distribution.models


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0006_merge_0005_follower_0005_post_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='share_from',
            field=models.UUIDField(default=None, null=True, verbose_name=social_distribution.models.Author),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default='', max_length=10000),
        ),
    ]
