# Generated by Django 3.1.6 on 2022-02-23 08:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0006_auto_20220223_0624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date_created',
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
