# Generated by Django 3.2.12 on 2022-04-04 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0007_auto_20220404_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='share_from',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared', to=settings.AUTH_USER_MODEL),
        ),
    ]
