# Generated by Django 3.1.6 on 2022-02-25 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0007_auto_20220223_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.URLField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='origin',
            field=models.URLField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='source',
            field=models.URLField(default=None, null=True),
        ),
    ]
