# Generated by Django 3.2.12 on 2022-03-22 03:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0007_auto_20220309_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='recepient',
            field=models.UUIDField(choices=[(uuid.UUID('6f9251fe-d195-48f5-8443-6c40259bd6d9'), 'try this'), (uuid.UUID('ab59474d-8c2e-404a-bd34-dce351980765'), 'try try'), (uuid.UUID('6e93d092-79ed-4d05-a5bb-2b205145f215'), 'Jejoon Ryu'), (uuid.UUID('518f649b-1e65-480a-a128-fb176f031df7'), 'Felipe Rodriguez'), (uuid.UUID('8d50aef8-a04b-45d8-a674-611d1829a68a'), 'Lara Croft')], default=None, null=True),
        ),
    ]
