# Generated by Django 3.2.12 on 2022-03-22 06:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0008_alter_post_recepient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='social_distribution.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_type',
            field=models.CharField(choices=[('text/plain', 'text'), ('text/markdown', 'markdown'), ('application/base64', 'application'), ('image/png;base64', 'png'), ('image/jpeg;base64', 'jpeg')], default='text/plain', max_length=18),
        ),
        migrations.AlterField(
            model_name='post',
            name='recepient',
            field=models.UUIDField(choices=[(uuid.UUID('6f9251fe-d195-48f5-8443-6c40259bd6d9'), 'try this'), (uuid.UUID('ab59474d-8c2e-404a-bd34-dce351980765'), 'try try'), (uuid.UUID('6e93d092-79ed-4d05-a5bb-2b205145f215'), 'Jejoon Ryu'), (uuid.UUID('518f649b-1e65-480a-a128-fb176f031df7'), 'Felipe Rodriguez')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('FRIENDS', 'Friends'), ('PRIVATE', 'Private')], default='PUBLIC', max_length=7),
        ),
    ]
