# Generated by Django 3.2.12 on 2022-02-25 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0008_auto_20220223_2151'),
        ('social_distribution', '0008_auto_20220225_0024'),
    ]

    operations = [
    ]
