# Generated by Django 3.2.12 on 2022-03-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0009_auto_20220322_0652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='object_id',
        ),
        migrations.AddField(
            model_name='like',
            name='object_url',
            field=models.URLField(default=None, editable=False, max_length=1000),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content_type',
            field=models.CharField(choices=[('text/plain', 'text'), ('text/markdown', 'markdown'), ('application/base64', 'application'), ('image/png;base64', 'png'), ('image/jpeg;base64', 'jpeg')], default='text/plain', max_length=18),
        ),
    ]
