# Generated by Django 3.2.12 on 2022-02-26 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0009_merge_0008_auto_20220223_2151_0008_auto_20220225_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='type',
            field=models.CharField(default='author', max_length=6),
        ),
    ]
