# Generated by Django 3.2.12 on 2022-03-22 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0010_auto_20220322_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='author_url',
            field=models.URLField(default=1, editable=False, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='like',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
