# Generated by Django 3.2.12 on 2022-02-26 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0012_auto_20220226_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='categories',
        ),
    ]
