# Generated by Django 3.1.6 on 2022-02-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0003_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.URLField()),
                ('url', models.URLField()),
                ('host', models.URLField()),
                ('display_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('github', models.URLField()),
                ('profile_image', models.URLField()),
            ],
        ),
    ]
