# Generated by Django 3.1.6 on 2022-02-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0007_auto_20220222_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.IntegerField(),
        ),
    ]
