# Generated by Django 3.1.6 on 2022-02-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0009_author_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(default=models.CharField(default=None, max_length=20, primary_key=True, serialize=False, unique=True)),
        ),
    ]
