# Generated by Django 3.1.6 on 2022-02-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0010_author_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='slug',
        ),
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.IntegerField(unique=True),
        ),
    ]
