# Generated by Django 3.2.12 on 2022-03-23 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.URLField()),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'ServerNode',
            },
        ),
    ]
