# Generated by Django 3.2.12 on 2022-03-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servernode',
            name='host',
            field=models.CharField(max_length=500),
        ),
    ]
