# Generated by Django 3.2.12 on 2022-03-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20220325_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servernode',
            old_name='password',
            new_name='receiving_password',
        ),
        migrations.RenameField(
            model_name='servernode',
            old_name='username',
            new_name='receiving_username',
        ),
        migrations.AddField(
            model_name='servernode',
            name='sending_password',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='servernode',
            name='sending_username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
