# Generated by Django 3.2.12 on 2022-03-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_servernode_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='servernode',
            name='is_local',
            field=models.BooleanField(default=False),
        ),
    ]
